# Generated by Django 4.0.3 on 2022-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='0000000', editable=False, max_length=8),
        ),
    ]
